
ticker_alternate : ['abbottindia' ,'bandhanbank','canfinhomes','cityunionbank','icicilombardgeneralinsurancecompany','irctc-indianrailwaycateringtourismcorp',
 'mahanagargas', 'nestleindia','pageindustries', 'sbicardspaymentservices', 'sbilifeinsurancecompany', 'ausmallfinancebank','abbindia','abbottindia','canfinhomes',
  'hdfcassetmanagementcompany','icicilombardgeneralinsurancecompany'  , 'irctc-indianrailwaycateringtourismcorp',
                   'mahanagargas','nestleindia','pageindustries','sbicardspaymentservices','sbilifeinsurancecompany']

tickers_NS : [ "ABB.NS", "ACC.NS","AUBANK.NS","AARTIIND.NS","ABBOTINDIA.NS",
          "ADANIENT.NS","ADANIPORTS.NS","ABCAPITAL.NS",
          "ABFRL.NS","ALKEM.NS", "AMBUJACEM.NS", "APOLLOHOSP.NS", "APOLLOTYRE.NS",
          "ASHOKLEY.NS","ASIANPAINT.NS","ASTRAL.NS","ATUL.NS","AUROPHARMA.NS","AXISBANK.NS",
          "BAJAJ-AUTO.NS","BAJFINANCE.NS","BAJAJFINSV.NS","BALKRISIND.NS","BALRAMCHIN.NS",
          "BANDHANBNK.NS","BANKBARODA.NS","BATAINDIA.NS","BERGEPAINT.NS","BEL.NS","BHARATFORG.NS",
          "BHEL.NS","BPCL.NS","BHARTIARTL.NS","BIOCON.NS","BSOFT.NS",
          "BOSCHLTD.NS","BRITANNIA.NS","CANFINHOME.NS","CANBK.NS","CHAMBLFERT.NS","CHOLAFIN.NS",
          "CIPLA.NS","CUB.NS","COALINDIA.NS","COFORGE.NS" ,"COLPAL.NS","CONCOR.NS","COROMANDEL.NS",
          "CROMPTON.NS","CUMMINSIND.NS","DLF.NS","DABUR.NS","DALBHARAT.NS","DEEPAKNTR.NS","DELTACORP.NS", "DIVISLAB.NS",
          "DIXON.NS","LALPATHLAB.NS","DRREDDY.NS","EICHERMOT.NS","ESCORTS.NS","EXIDEIND.NS","FEDERALBNK.NS","GAIL.NS",
          "GMRINFRA.NS","GLENMARK.NS","GODREJCP.NS","GODREJPROP.NS","GRANULES.NS","GRASIM.NS","GUJGASLTD.NS",
          "GNFC.NS","HCLTECH.NS","HDFCAMC.NS","HDFCBANK.NS","HDFCLIFE.NS","HAVELLS.NS","HEROMOTOCO.NS",
          "HINDALCO.NS","HAL.NS","HINDCOPPER.NS","HINDPETRO.NS","HINDUNILVR.NS","ICICIBANK.NS","ICICIGI.NS",
          "ICICIPRULI.NS","IDFCFIRSTB.NS","IDFC.NS","ITC.NS","INDIACEM.NS", "IBULHSGFIN.NS", "INDIAMART.NS","IEX.NS","INDHOTEL.NS",
          "IOC.NS","IRCTC.NS","IGL.NS","INDUSTOWER.NS","INDUSINDBK.NS","NAUKRI.NS", "INFY.NS","INDIGO.NS","IPCALAB.NS",
          "JKCEMENT.NS","JSWSTEEL.NS","JINDALSTEL.NS","JUBLFOOD.NS", "KOTAKBANK.NS","L&TFH.NS","LTTS.NS","LICHSGFIN.NS","LTIM.NS","LT.NS",
          "LAURUSLABS.NS", "LUPIN.NS","MRF.NS","MGL.NS","M&MFIN.NS","M&M.NS","MANAPPURAM.NS","MARICO.NS","MARUTI.NS","MFSL.NS",
          "METROPOLIS.NS", "MPHASIS.NS","MCX.NS","MUTHOOTFIN.NS","NMDC.NS","NTPC.NS","NATIONALUM.NS","NAVINFLUOR.NS",
          "NESTLEIND.NS","OBEROIRLTY.NS","ONGC.NS","OFSS.NS","PIIND.NS","PVRINOX.NS","PAGEIND.NS","PERSISTENT.NS",
          "PETRONET.NS","PIDILITIND.NS","PEL.NS","POLYCAB.NS","PFC.NS","POWERGRID.NS","PNB.NS","RBLBANK.NS",
          "RECLTD.NS","RELIANCE.NS","SBICARD.NS","SBILIFE.NS","SRF.NS","MOTHERSON.NS","SHREECEM.NS","SHRIRAMFIN.NS","SIEMENS.NS","SBIN.NS",
          "SAIL.NS","SUNPHARMA.NS","SUNTV.NS","SYNGENE.NS","TVSMOTOR.NS","TATACHEM.NS","TATACOMM.NS","TCS.NS","TATACONSUM.NS",
          "TATAMOTORS.NS", "TATAPOWER.NS","TATASTEEL.NS","TECHM.NS","RAMCOCEM.NS","TITAN.NS","TORNTPHARM.NS","TRENT.NS", "UPL.NS","ULTRACEMCO.NS","UBL.NS","MCDOWELL-N.NS",
          "VEDL.NS","IDEA.NS","VOLTAS.NS","WIPRO.NS","ZEEL.NS","ZYDUSLIFE.NS"]


tickers : [ "abbindia", "acc","ausmallfinancebank","aartiindustries","abbottindia",
          "adanienterprises","adaniportsspecialeconomiczone","adityabirlacapital",
          "adityabirlafashionretail","alkemlaboratories", "ambujacements", "apollohospitalsenterprises", "apollotyres",
          "ashokleyland","asianpaints","astrallimited","atul","aurobindopharma","axisbank",
          "bajajauto","bajajfinance","bajajfinserv","balkrishnaindustries","balrampurchinimills",
          "bandhanbank","bankbaroda","bataindia","bergerpaintsindia","bharatelectronics","bharatforge",
          "bharatheavyelectricals","bharatpetroleumcorporation","bhartiairtel","biocon","birlasoft",
          "bosch","britanniaindustries","canfinhomes","canarabank","chambalfertiliserschemicals","cholamandalaminvestmentfinancecompany",
          "cipla","cityunionbank","coalindia","coforgelimited" ,"colgatepalmoliveindia","containercorporationindia","coromandelinternational",
          "cromptongreavesconsumerelectrical","cumminsindia","dlf","daburindia","dalmiabharat","deepaknitrite","deltacorp", "divislaboratories",
          "dixontechnologies","drlalpathlabs","drreddyslaboratories","eichermotors","escortskubota","exideindustries","federalbank","gailindia",
          "gmrairportsinfrastructure","glenmarkpharma","godrejconsumerproducts","godrejproperties","granulesindia","grasimindustries","gujaratgas",
          "gujaratnarmadavalleyfertchem","hcltechnologies","hdfcassetmanagementcompany","hdfcbank","hdfclifeinsurancecompany","havellsindia","heromotocorp",
          "hindalcoindustries","hindustanaeronauticsltd","hindustancopper","hindustanpetroleumcorporation","hindustanunilever","icicibank","icicilombardgeneralinsurancecompany",
          "iciciprudentiallifeinsurancecompany","idfcfirstbank","idfc","itc","indiacements", "indiabullshousingfinance", "indiamartintermesh","indianenergyexchange","indianhotelscompany",
          "indianoilcorporation","irctc-indianrailwaycateringtourismcorp","indraprasthagas","industowers","indusindbank","infoedgeindia", "infosys","interglobeaviation","ipcalaboratories",
          "jkcement","jswsteel","jindalsteelpower","jubilantfoodworks", "kotakmahindrabank","ltfinanceholdings","lttechnologyservices","lichousingfinance","ltimindtree","larsentoubro",
          "lauruslabs", "lupin","mrf","mahanagargas","mahindramahindrafinancialservices","mahindramahindra","manappuramfinance","marico","marutisuzukiindia","maxfinancialservices",
          "metropolishealthcare", "mphasis","multicommodityexchangeindia","muthootfinance","nmdc","ntpc","nationalaluminiumcompany","navinfluorineinternational",
          "nestleindia","oberoirealty","oilnaturalgascorporation","oraclefinancialservicessoftware","piindustries","pvrinox","pageindustries","persistentsystems",
          "petronetlng","pidiliteindustries","piramalenterprises","polycabindia","powerfinancecorporation","powergridcorporationindia","punjabnationalbank","rblbank",
          "rec","relianceindustries","sbicardspaymentservices","sbilifeinsurancecompany","srf","samvardhanamothersoninternational","shreecements","shriramfinance","siemens","statebankindia",
          "steelauthorityindia","sunpharmaceuticalindustries","suntvnetwork","syngeneinternational","tvsmotorcompany","tatachemicals","tatacommunications","tataconsultancyservices","tataconsumerproducts",
          "tatamotors", "thetatapowercompany","tatasteel","techmahindra","theramcocements","titancompany","torrentpharmaceuticals","trent", "upl","ultratechcement","unitedbreweries","unitedspirits",
          "vedanta","vodafoneidealimited","voltas","wipro","zeeentertainmententerprises","zyduslifesciences"]

ti : [ "ABB", "ACC06","ASF02","AI45","AI51","AE13","MPS","ABC9","PFR","AL05","AC18","AHE" ,"AT14",
     "AL","AP31","APT02","A06","AP","AB16","BA10","BAF","BF04","BI03","BCM","BB09","BOB","BI01",
     "BPI02","BE03","BF03","BHE","BPC","BA08","BL03","KPI02","B05","BI","CFH","CB06","CFC","CDB",
     "C","CUB","CI11","NII02","CPI","CCI","CI45","CGC01","CI02","D04","DI","OCL","DN","DC11","DL03",
      "DT07","DLP01","DRL","EM", "E","EI","FB","GAI","GI27","GP08","GCP","GP11","GI25","GI01","GGC","GNV",
      "HCL02","HAM02","HDF01","HSL01","HI01","HHM","HI","HAL","HC07","HPC","HU","ICI02","ILG","IPL01","IDF01",
      "IDF","ITC","IC", "IHF01", "II12","IEE","IHC","IOC","IRC","IG04","BI14","IIB","IEI01","IT", "IA04","IL",
      "JKC03","JSW01","JSP", "JF04","KMB","LFH","LTS","LIC","LI12","LT","LL05","L","MRF","MG02","MMF04","MM","MGF01",
      "M13","MS24","MI","MH06","MB02","MCE","MF10","NMD02","NTP","NAC","NFI","NI","OR","ONG","OFS01","PII","PVR","PI35","PS15",
      "PLN","PI11","PH05","PI44","PFC02","PGC","PNB05","RB03","REC02","RI","SCP02","SLI03","SRF","MSS01","SC12","STF","S","SBI",
      "SAI","SPI","STN01","SI10","TVS","TC","TC17","TCS","TT","TM03","TPC","TIS","TM4","MC","TI01","TP06","T04","UP04","UTC01","UB02",
      "US","SG","IC8","V","W","ZEE","CHC"
     ]

sector :
  abbindia : "infrastructure-general"
  acc : "cement-major"
  ausmallfinancebank : "banks-private-sector"
  aartiindustries: "chemicals"
  abbottindia : "pharmaceuticals"
  adanienterprises: "trading"
  adaniportsspecialeconomiczone : "infrastructure-general"
  adityabirlacapital : "finance-investments"
  adityabirlafashionretail : "retail"
  alkemlaboratories: "pharmaceuticals"
  ambujacements: "cement-major"
  apollohospitalsenterprises : "hospitalsmedical-services"
  apollotyres : "tyres"
  ashokleyland: "auto-lcvshcvs"
  asianpaints : "paintsvarnishes"
  astrallimited : "plastics"
  atul : "chemicals"
  aurobindopharma : "pharmaceuticals"
  axisbank : "banks-private-sector"
  bajajauto: "auto-23-wheelers"
  bajajfinance: "finance-nbfc"
  bajajfinserv:  "finance-nbfc"
  balkrishnaindustries: "tyres"
  balrampurchinimills: "sugar"
  bandhanbank:  "banks-private-sector"
  bankbaroda: "banks-public-sector"
  bataindia: "leather-products"
  bergerpaintsindia: "paintsvarnishes"
  bharatelectronics: "aerospacedefence"
  bharatforge: "castingsforgings"
  bharatheavyelectricals: "infrastructure-general"
  bharatpetroleumcorporation: "refineries"
  bhartiairtel: "telecommunications-service"
  biocon: "pharmaceuticals"
  birlasoft: "computers-software-mediumsmall"
  bosch: "auto-ancillaries"
  britanniaindustries: "food-processing"
  canfinhomes: "finance-housing"
  canarabank: "banks-public-sector"
  chambalfertiliserschemicals:  "fertilisers"
  cholamandalaminvestmentfinancecompany: "finance-nbfc"
  cipla: "pharmaceuticals"
  cityunionbank: "banks-private-sector"
  coalindia: "miningminerals"
  coforgelimited: "computers-software"
  colgatepalmoliveindia: "personal-care"
  containercorporationindia: "transportlogistics"
  coromandelinternational: "fertilisers"
  cromptongreavesconsumerelectrical: "electricals"
  cumminsindia: "engines"
  dlf: "constructioncontracting-real-estate"
  daburindia: "personal-care"
  dalmiabharat: "cement-major"
  deepaknitrite: "chemicals"
  deltacorp: "constructioncontracting-real-estate"
  divislaboratories: "pharmaceuticals"
  dixontechnologies: "electricals"
  drlalpathlabs: "pharmaceuticals"
  drreddyslaboratories: "pharmaceuticals"
  eichermotors: "auto-lcvshcvs"
  escortskubota: "automobile-tractors"
  exideindustries: "auto-ancillaries"
  federalbank: "banks-private-sector"
  gailindia: "oil-drillingexploration"
  gmrairportsinfrastructure: "transport-infrastructure"
  glenmarkpharma: "pharmaceuticals"
  godrejconsumerproducts: "personal-care"
  godrejproperties: "constructioncontracting-real-estate"
  granulesindia: "pharmaceuticals"
  grasimindustries: "diversified"
  gujaratgas: "oil-drillingexploration"
  gujaratnarmadavalleyfertchem: "gujaratnarmadavalleyfertchem"
  hcltechnologies: "computers-software"
  hdfcassetmanagementcompany: "finance-investments"
  hdfcbank: "banks-private-sector"
  hdfclifeinsurancecompany: "lifehealth-insurance"
  havellsindia: "electric-equipment"
  heromotocorp: "auto-23-wheelers"
  hindalcoindustries: "ironsteel"
  hindustanaeronauticsltd: "diversified"
  hindustancopper: "metals-non-ferrous"
  hindustanpetroleumcorporation: "refineries"
  hindustanunilever: "personal-care"
  icicibank: "banks-private-sector"
  icicilombardgeneralinsurancecompany: "multiline-insurancebrokers"
  iciciprudentiallifeinsurancecompany: "finance-general"
  idfcfirstbank: "banks-private-sector"
  idfc: "finance-housing"
  itc: "diversified"
  indiacements: "cement-major"
  indiabullshousingfinance: "finance-housing"
  indiamartintermesh:  "miscellaneous"
  indianenergyexchange: "diversified"
  indianhotelscompany: "hotels"
  indianoilcorporation: "refineries"
  irctc-indianrailwaycateringtourismcorp: "miscellaneous"
  indraprasthagas: "oil-drillingexploration"
  industowers: "telecommunications-equipment"
  indusindbank: "banks-private-sector"
  infoedgeindia: "miscellaneous"
  infosys: "computers-software"
  interglobeaviation: "transportlogistics"
  ipcalaboratories: "pharmaceuticals"
  jkcement: "cement-major"
  jswsteel: "steel-large"
  jindalsteelpower: "steel-sponge-iron"
  jubilantfoodworks: "miscellaneous"
  kotakmahindrabank: "banks-private-sector"
  ltfinanceholdings: "finance-investments"
  lttechnologyservices: "engineering"
  lichousingfinance: "finance-housing"
  ltimindtree: "computers-software"
  larsentoubro: "infrastructure-general"
  lauruslabs: "pharmaceuticals"
  lupin: "pharmaceuticals"
  mrf: "tyres"
  mahanagargas: "refineries"
  mahindramahindrafinancialservices: "finance-nbfc"
  mahindramahindra: "auto-carsjeeps"
  manappuramfinance: "finance-leasinghire-purchase"
  marico: "personal-care"
  marutisuzukiindia: "auto-carsjeeps"
  maxfinancialservices: "finance-investments"
  metropolishealthcare: "hospitalsmedical-services"
  mphasis: "computers-software"
  multicommodityexchangeindia: "miscellaneous"
  muthootfinance: "finance-investments"
  nmdc: "miningminerals"
  ntpc: "power-generationdistribution"
  nationalaluminiumcompany: "aluminium"
  navinfluorineinternational: "chemicals"
  nestleindia: "food-processing"
  oberoirealty: "constructioncontracting-real-estate"
  oilnaturalgascorporation: "oil-drillingexploration"
  oraclefinancialservicessoftware: "computers-software"
  piindustries: "pesticidesagro-chemicals"
  pvrinox: "mediaentertainment"
  pageindustries: "textiles-readymade-apparels"
  persistentsystems: "computers-software"
  petronetlng: "oil-drillingexploration"
  pidiliteindustries: "chemicals"
  piramalenterprises: "finance-nbfc"
  polycabindia: "cables-powerothers"
  powerfinancecorporation: "finance-term-lending-institutions"
  powergridcorporationindia: "power-generationdistribution"
  punjabnationalbank: "banks-public-sector"
  rblbank: "banks-private-sector"
  rec: "finance-term-lending-institutions"
  relianceindustries: "refineries"
  sbicardspaymentservices: "finance-term-lending"
  sbilifeinsurancecompany: "lifehealth-insurance"
  srf: "diversified"
  samvardhanamothersoninternational: "auto-ancillaries-auto-truckmotorcycle-parts"
  shreecements: "cement-major"
  shriramfinance: "finance-leasinghire-purchase"
  siemens: "infrastructure-general"
  statebankindia: "banks-public-sector"
  steelauthorityindia: "steel-large"
  sunpharmaceuticalindustries: "pharmaceuticals"
  suntvnetwork: "mediaentertainment"
  syngeneinternational: "miscellaneous"
  tvsmotorcompany: "auto-23-wheelers"
  tatachemicals: "chemicals"
  tatacommunications: "telecommunications-service"
  tataconsultancyservices: "computers-software"
  tataconsumerproducts: "plantations-teacoffee"
  tatamotors: "auto-lcvshcvs"
  thetatapowercompany: "power-generationdistribution"
  tatasteel: "ironsteel"
  techmahindra: "computers-software"
  theramcocements: "cement-major"
  titancompany: "miscellaneous"
  torrentpharmaceuticals: "pharmaceuticals"
  trent: "retail"
  upl: "chemicals"
  ultratechcement: "cement-major"
  unitedbreweries: "breweriesdistilleries"
  unitedspirits: "breweriesdistilleries"
  vedanta: "miningminerals"
  vodafoneidealimited: "telecommunications-service"
  voltas: "diversified"
  wipro: "computers-software"
  zeeentertainmententerprises: "mediaentertainment"
  zyduslifesciences: "pharmaceuticalsdrugs"
