keyword_mapping :
    "ABB.NS" : [r"\bABB\b", r"\bABB India", "Asea Brown Boveri"]
    "ACC.NS" : [r"\bACC\b", "Associated Cement CompaniesAssociated Cement Companies"]
    "AUBANK.NS" : ["AU Small Finance"]
    "AARTIIND.NS" : ["Aarti", "Aarti Industries"]
    "ABBOTINDIA.NS" : ["Abbott", "Abbot India"]
    "ADANIENT.NS" : [ "Adani Enterprise"]
    "ADANIPORTS.NS" : ["Adani Port"]
    "ABCAPITAL.NS" : ["AB Capital", "Aditya Birla Capital"]
    "ABFRL.NS" : ["Aditya Birla Fashion"]
    "ALKEM.NS" : ["Alkem Lab", "Alkem Laboratory", "Alkem Laboratories"]
    "AMBUJACEM.NS" : ["Ambuja Cement"]
    "APOLLOHOSP.NS" : ["Apollo Hospital"]
    "APOLLOTYRE.NS" : ["Apollo Tyre"]
    "ASHOKLEY.NS" : ["Ashok Leyland"]
    "ASIANPAINT.NS" : ["Asian Paint"]
    "ASTRAL.NS" : ["Astral", "Atral Limited"]
    "ATUL.NS" : ["Atul Limited", "Atul"]
    "AUROPHARMA.NS" : ["Aurobindo", "Aurobindo Pharma"]
    "AXISBANK.NS" : ["Axis Bank"]
    "BAJAJ-AUTO.NS" : ["Bajaj Auto"]
    "BAJFINANCE.NS" : ["Bajaj Finance"]
    "BAJAJFINSV.NS" : ["Bajaj Finserv"]
    "BALKRISIND.NS" : ["Balkrishna Industries"]
    "BALRAMCHIN.NS" : ["Balrampur Chini"]
    "BANDHANBNK.NS" : [" Bandhan Bank"]
    "BANKBARODA.NS" : ["Bank of Baroda", "Baroda Bank"]
    "BATAINDIA.NS": ["Bata India"]
    "BERGEPAINT.NS" : ["Berger Paint"]
    "BEL.NS" : ["Bharat Electronic", "Bharat Electronics Limited", "Bharat Electronics Ltd"]
    "BHARATFORG.NS" : ["Bharat Forge"]
    "BHEL.NS" : ["Bharat Heavy", "Bharat Heavy Electrical"]
    "BPCL.NS" : ["Bharat Petroleum"]
    "BHARTIARTL.NS" : ["Bharti Airtel", "Airtel"]
    "BIOCON.NS" : ["Biocon"]
    "BSOFT.NS": ["Birla Soft", "BirlaSoft", "KPIT", "Cummins", "Kirtaney Pandit"]
    "BOSCHLTD.NS" : ["Bosch Limited", "Bosch"]
    "BRITANNIA.NS": ["Britannia Industries", "Britannia"]
    "CANFINHOME.NS" : ["Can Fin", "CanFin"]
    "CANBK.NS" : ["Canara"]
    "CHAMBLFERT.NS" : ["Chambal", "Chambal Fertili"]
    "CHOLAFIN.NS" : ["Cholamandalam"]
    "CIPLA.NS" : ["Cipla"]
    "CUB.NS" : ["City Union" , "CityUnion"]
    "COALINDIA.NS" : ["Coal India", "CoalIndia"]
    "COFORGE.NS" : ["Coforge", "Co Forge"]
    "COLPAL.NS" : ["Colgate-Palmolive", "ColPal", "ColgatePalmolive", "Colgate Palmolive"]
    "CONCOR.NS" : ["Concor", "Container Corporation"]
    "COROMANDEL.NS" : ["COROMANDEL", "COROMANDEL International"]
    "CROMPTON.NS" : ["CROMPTON"]
    "CUMMINSIND.NS" : ["Cummins"]
    "DLF.NS" : [r"\bDLF\b", "Delhi Land & Finance"]
    "DABUR.NS" : ["DABUR"]
    "DALBHARAT.NS" : ["Dalmia", "DalmiaBharat"]
    "DEEPAKNTR.NS" : ["DeepakNitrite", "Deepak Nitrite"]
    "DELTACORP.NS" : ["DeltaCorp", "Delta Corp"]
    "DIVISLAB.NS" : ["divi's lab", "divi lab", "divilab","DIVISLAB"]
    "DIXON.NS" : ["Dixon"]
    "LALPATHLAB.NS" : ["DR LAL PATHLABS", "DRLALPATHLABS", "LALPATHLABS", "LAL PATHLABS", "lal path", "lal lab","lalpath","lallab"]
    "DRREDDY.NS" : ["dr reddy", "drreddy"]
    "EICHERMOT.NS" : ["eicher", "eicher mot","eichermot"]
    "ESCORTS.NS" : ["escorts", "escortkubota", "kubota"]
    "EXIDEIND.NS" : ["exide","exideind"]
    "FEDERALBNK.NS" : ["federal bank", "FEDERALBNK"]
    "GAIL.NS" : [r"\bgail\b","Gas Authority Of India", "GasAuthorityOfIndia", "Gas Authority India"]
    "GMRINFRA.NS" : ["GMRAirport", "GMR"]
    "GLENMARK.NS" : ["Glenmark"]
    "GODREJCP.NS" : ["GodrejCon","Godrej Con"]
    "GODREJPROP.NS" : ["Godrejprop", "Godrej Prop"]
    "GRANULES.NS": ["granulesindia", "granules india"]
    "GRASIM.NS" : ["grasim ind", "grasim", "grasimind"]
    "GUJGASLTD.NS" : ["gujarat gas", "gujaratgas"]
    "GNFC.NS" : ["gnfc", "Gujarat Narmada Valley Fertilizer", "Gujarat Narmada Valley Fertilizer"]
    "HCLTECH.NS" : ["HCL", "Hcl tech", "hcltech", "Hindustan Computer", "HindustanComputer"]
    "HDFCAMC.NS" : ["hdfc asset", "hdfcasset"]
    "HDFCBANK.NS" : ["hdfc bank", "hdfcbank", "Housing Development Finance","HousingDevelopmentFinance"]
    "HDFCLIFE.NS" : ["hdfc life", "hdfclife"]
    "HAVELLS.NS" : ["havells","havellsindia"]
    "HEROMOTOCO.NS" : ["HEROMOTO", "hero moto"]
    "HINDALCO.NS" : ["hindalco", "Hindustan Aluminium", "HindustanAluminium"]
    "HAL.NS" : ["Hindustan Aero", "HindustanAero"]
    "HINDCOPPER.NS" : ["HINDCOPPER", "HIND COPPER", "Hindustan Copper", "HindustanCopper"]
    "HINDPETRO.NS" : ["HINDPETRO", "HIND PETRO", "Hindustan Petro",  "HindustanPetro"]
    "HINDUNILVR.NS" : ["HINDUNILVR", "HIND UNILVR", "hindustan uni", "hindustanuni"]
    "ICICIBANK.NS" : ["icici bank", "icicibank"]
    "ICICIGI.NS" : ["icici lombard", "icicilombard"]
    "ICICIPRULI.NS" : ["icici prudential", "icici pru", "icicipru"]
    "IDFCFIRSTB.NS" : ["idfc first", "idfc bank"]
    "IDFC.NS" : ["idfc", "Infrastructure Development Finance"]
    "ITC.NS" : ["Imperial Tobacco Company", r"\bitc\b"]
    "INDIACEM.NS" : ["india cement","indiacem"]
    "IBULHSGFIN.NS" : ["Indiabulls", "Indiabulls Housing", "IndiabullsHousing"]
    "INDIAMART.NS" : ["indiamart", "intermesh"]
    "IEX.NS" : [r"\biex\b", "Indian Energy Exchange", "IndianEnergyExchange"]
    "INDHOTEL.NS" : ["Indian Hotel", "IndianHotel"]
    "IOC.NS" : ["indian oil", "indianoil"]
    "IRCTC.NS" : ["irctc", "Indian Railway Catering", "IndianRailwayCatering"]
    "IGL.NS" : ["Indraprastha Gas", "IndraprasthaGas"]
    "INDUSTOWER.NS" : ["INDUS TOWER", "INDUSTOWER"]
    "INDUSINDBK.NS" : ["IndusInd", "IndusInd bank", "IndusIndbank"]
    "NAUKRI.NS" : ["infoedge","info edge", "naukri"]
    "INFY.NS" : ["infosys"]
    "INDIGO.NS" : ["interglobe aviation", "interglobeaviation"]
    "IPCALAB.NS" : ["ipca lab","ipcalab"]
    "JKCEMENT.NS" : ["JKCEMENT","j k cement", "jk cement"]
    "JSWSTEEL.NS" : ["jswsteel", "jsw steel", "j s w steel"]
    "JINDALSTEL.NS" : ["jindal steel", "jindalsteel"]
    "JUBLFOOD.NS" : ["Jubilant FoodWork", "JubilantFoodWork"]
    "KOTAKBANK.NS" : ["kotak bank", "kotak mahindra", "kotakbank", "kotakmahindra"]
    "L&TFH.NS" : ["L&T Finance", "L&TFinance"]
    "LTTS.NS" : ["L&T Tech","L&TTech"]
    "LICHSGFIN.NS" : ["LIC Housing","LICHousing"]
    "LTIM.NS" : ["LTIMindtree", "LTI Mindtree"]
    "LT.NS" : ["Larsen & Toubro", "Larsen&Toubro"]
    "LAURUSLABS.NS" : ["Lauruslab","Laurus lab"]
    "LUPIN.NS" : ["lupin"]
    "MRF.NS" : [r"\bMRF\b","M.R.F", "Madras Rubber Factory", "MadrasRubberFactory"]
    "MGL.NS" : ["Mahanagar Gas", "MahanagarGas"]
    "M&MFIN.NS" : ["M&MFIN", "Mahindra & Mahindra Fin", "Mahindra Fin", "MahindraFin"]
    "M&M.NS" : ["Mahindra & Mahindra", r"\bm&m\b", "Mahindra&Mahindra"]
    "MANAPPURAM.NS" : ["Manappuram", "Manappuram Fin"]
    "MARICO.NS" : ["marico"]
    "MARUTI.NS" : ["maruti", "suzuki"]
    "MFSL.NS" : ["MaxFin", "Max Fin"]
    "METROPOLIS.NS" : ["metropolis health", "meropolishealth"]
    "MPHASIS.NS" : [r"\bMphasis\b"]
    "MCX.NS" : ["multicommodityexchange", "multi commodity exchange"]
    "MUTHOOTFIN.NS" : ["Muthoot Fin", "MuthootFin"]
    "NMDC.NS" : [r"\bNMDC\b", "National Mineral Development","NationalMineral"]
    "NTPC.NS" : [r"\bNTPC\b", "National thermal"]
    "NATIONALUM.NS" : ["national aluminium", "nationalaluminium"]
    "NAVINFLUOR.NS" : ["Navin Fluorine", "NavinFluorine"]
    "NESTLEIND.NS" : ["Nestle India", "NestleIndia"]
    "OBEROIRLTY.NS" : ["Oberoi Realty", "OberoiRealty"]
    "ONGC.NS" : [r"\bongc\b","Oil and Natural Gas"]
    "OFSS.NS" : ["Oracle Financial Service"]
    "PIIND.NS" : ["PI Ind"]
    "PVRINOX.NS" : [r"\bpvr\b", "Priya Village Road", "Priya Vill","PriyaVill"]
    "PAGEIND.NS" : ["Page Industr", "PageIndustr"]
    "PERSISTENT.NS" : ["Persistent System", "PersistentSystem"]
    "PETRONET.NS" : ["Petronet","Petronet LNG", "PetronetLNG"]
    "PIDILITIND.NS" : ["Pidilite Ind", "Pidilite"]
    "PEL.NS" : ["Piramal"]
    "POLYCAB.NS" : ["Polycab"]
    "PFC.NS" : ["Power Finance","PowerFin"]
    "POWERGRID.NS" : ["Power Grid","PowerGrid"]
    "PNB.NS" : ["pnb","Punjab National Bank"]
    "RBLBANK.NS" : ["RBL BANK", "RBLBANK"]
    "RECLTD.NS" : ["Rural Electrification Corporation", "Rural Electrification Corp", "RuralElectrificationCorp"]
    "RELIANCE.NS" : [r"\bRIL\b", "RELIANCE IND"]
    "SBICARD.NS" : ["SBICARD", "SBI CARD"]
    "SBILIFE.NS" : ["SBI Life", "SBILIFE"]
    "SRF.NS" : [r"\bSRF\b"]
    "MOTHERSON.NS" : ["Samvardhana", "Motherson"]
    "SHREECEM.NS" : ["ShreeCem", "SHREE CEM"]
    "SHRIRAMFIN.NS" : ["Shriram Fin"]
    "SIEMENS.NS" : ["Siemen"]
    "SBIN.NS" : [r"\bsbi\b", "State Bank Of India"]
    "SAIL.NS" : ["Steel Authority of India Ltd", "sail"]
    "SUNPHARMA.NS" : ["Sun Pharma","SunPharma"]
    "SUNTV.NS" : ["Sun TV", "SunTV"]
    "SYNGENE.NS" : ["SYNGENE"]
    "TVSMOTOR.NS" : [r"\bTVS\b", "Thirukkurungudi Vengaram Sundram"]
    "TATACHEM.NS" : ["TATA Chem", "TATAChem"]
    "TATACOMM.NS" : ["Tata Comm", "TataComm"]
    "TCS.NS" : ["TCS","Tata Consultancy","TataConsultancy"]
    "TATACONSUM.NS" : ["Tata Consumer","TataConsumer"]
    "TATAMOTORS.NS" : ["Tata Motor","TataMotor"]
    "TATAPOWER.NS" : ["Tata Power", "TataPower"]
    "TATASTEEL.NS" : ["Tata Steel", "TataSteel"]
    "TECHM.NS" : ["Tech Mahindra","TechMahindra"]
    "RAMCOCEM.NS" : ["ramcocem","ramco cem"]
    "TITAN.NS" : ["titan"]
    "TORNTPHARM.NS" : ["torrent pharma", "torrentpharma","TORNTPHARM"]
    "TRENT.NS" : ["trent"]
    "UPL.NS" : [r"\bUPL\b", "United Phosphorus", "UnitedPhosphorus"]
    "ULTRACEMCO.NS" : ["UltraTech"]
    "UBL.NS" : ["United Brewer", r"\bubl\b"]
    "MCDOWELL-N.NS" : ["MCDOWELL", "united spirit", "unitedspirit"]
    "VEDL.NS" : ["Vedanta"]
    "IDEA.NS" : ["idea", "Vodafone Idea"]
    "VOLTAS.NS" : ["VOLTAS"]
    "WIPRO.NS" : ["wipro"]
    "ZEEL.NS" : ["Zee Entertainment", "ZeeEntertainment"]
    "ZYDUSLIFE.NS" : ["zydus"]



tickers_NS : ["ABB.NS", "ACC.NS","AUBANK.NS","AARTIIND.NS","ABBOTINDIA.NS",
          "ADANIENT.NS","ADANIPORTS.NS","ABCAPITAL.NS",
          "ABFRL.NS","ALKEM.NS", "AMBUJACEM.NS", "APOLLOHOSP.NS", "APOLLOTYRE.NS",
          "ASHOKLEY.NS","ASIANPAINT.NS","ASTRAL.NS","ATUL.NS","AUROPHARMA.NS","AXISBANK.NS",
          "BAJAJ-AUTO.NS","BAJFINANCE.NS","BAJAJFINSV.NS","BALKRISIND.NS","BALRAMCHIN.NS",
          "BANDHANBNK.NS","BANKBARODA.NS","BATAINDIA.NS","BERGEPAINT.NS","BEL.NS","BHARATFORG.NS",
          "BHEL.NS","BPCL.NS","BHARTIARTL.NS","BIOCON.NS","BSOFT.NS",
          "BOSCHLTD.NS","BRITANNIA.NS","CANFINHOME.NS","CANBK.NS","CHAMBLFERT.NS","CHOLAFIN.NS",
          "CIPLA.NS","CUB.NS","COALINDIA.NS","COFORGE.NS" ,"COLPAL.NS","CONCOR.NS","COROMANDEL.NS",
          "CROMPTON.NS","CUMMINSIND.NS","DLF.NS","DABUR.NS","DALBHARAT.NS","DEEPAKNTR.NS","DELTACORP.NS", "DIVISLAB.NS",
          "DIXON.NS","LALPATHLAB.NS","DRREDDY.NS","EICHERMOT.NS","ESCORTS.NS","EXIDEIND.NS","FEDERALBNK.NS","GAIL.NS",
          "GMRINFRA.NS","GLENMARK.NS","GODREJCP.NS","GODREJPROP.NS","GRANULES.NS","GRASIM.NS","GUJGASLTD.NS",
          "GNFC.NS","HCLTECH.NS","HDFCAMC.NS","HDFCBANK.NS","HDFCLIFE.NS","HAVELLS.NS","HEROMOTOCO.NS",
          "HINDALCO.NS","HAL.NS","HINDCOPPER.NS","HINDPETRO.NS","HINDUNILVR.NS","ICICIBANK.NS","ICICIGI.NS",
          "ICICIPRULI.NS","IDFCFIRSTB.NS","IDFC.NS","ITC.NS","INDIACEM.NS", "IBULHSGFIN.NS", "INDIAMART.NS","IEX.NS","INDHOTEL.NS",
          "IOC.NS","IRCTC.NS","IGL.NS","INDUSTOWER.NS","INDUSINDBK.NS","NAUKRI.NS", "INFY.NS","INDIGO.NS","IPCALAB.NS",
          "JKCEMENT.NS","JSWSTEEL.NS","JINDALSTEL.NS","JUBLFOOD.NS", "KOTAKBANK.NS","L&TFH.NS","LTTS.NS","LICHSGFIN.NS","LTIM.NS","LT.NS",
          "LAURUSLABS.NS", "LUPIN.NS","MRF.NS","MGL.NS","M&MFIN.NS","M&M.NS","MANAPPURAM.NS","MARICO.NS","MARUTI.NS","MFSL.NS",
          "METROPOLIS.NS", "MPHASIS.NS","MCX.NS","MUTHOOTFIN.NS","NMDC.NS","NTPC.NS","NATIONALUM.NS","NAVINFLUOR.NS",
          "NESTLEIND.NS","OBEROIRLTY.NS","ONGC.NS","OFSS.NS","PIIND.NS","PVRINOX.NS","PAGEIND.NS","PERSISTENT.NS",
          "PETRONET.NS","PIDILITIND.NS","PEL.NS","POLYCAB.NS","PFC.NS","POWERGRID.NS","PNB.NS","RBLBANK.NS",
          "RECLTD.NS","RELIANCE.NS","SBICARD.NS","SBILIFE.NS","SRF.NS","MOTHERSON.NS","SHREECEM.NS","SHRIRAMFIN.NS","SIEMENS.NS","SBIN.NS",
          "SAIL.NS","SUNPHARMA.NS","SUNTV.NS","SYNGENE.NS","TVSMOTOR.NS","TATACHEM.NS","TATACOMM.NS","TCS.NS","TATACONSUM.NS",
          "TATAMOTORS.NS", "TATAPOWER.NS","TATASTEEL.NS","TECHM.NS","RAMCOCEM.NS","TITAN.NS","TORNTPHARM.NS","TRENT.NS", "UPL.NS","ULTRACEMCO.NS","UBL.NS","MCDOWELL-N.NS",
          "VEDL.NS","IDEA.NS","VOLTAS.NS","WIPRO.NS","ZEEL.NS","ZYDUSLIFE.NS"]


tickers : ["abbindia", "acc","ausmallfinancebank","aartiindustries","abbottindia",
          "adanienterprises","adaniportsspecialeconomiczone","adityabirlacapital",
          "adityabirlafashionretail","alkemlaboratories", "ambujacements", "apollohospitalsenterprises", "apollotyres",
          "ashokleyland","asianpaints","astrallimited","atul","aurobindopharma","axisbank",
          "bajajauto","bajajfinance","bajajfinserv","balkrishnaindustries","balrampurchinimills",
          "bandhanbank","bankbaroda","bataindia","bergerpaintsindia","bharatelectronics","bharatforge",
          "bharatheavyelectricals","bharatpetroleumcorporation","bhartiairtel","biocon","birlasoft",
          "bosch","britanniaindustries","canfinhomes","canarabank","chambalfertiliserschemicals","cholamandalaminvestmentfinancecompany",
          "cipla","cityunionbank","coalindia","coforgelimited" ,"colgatepalmoliveindia","containercorporationindia","coromandelinternational",
          "cromptongreavesconsumerelectrical","cumminsindia","dlf","daburindia","dalmiabharat","deepaknitrite","deltacorp", "divislaboratories",
          "dixontechnologies","drlalpathlabs","drreddyslaboratories","eichermotors","escortskubota","exideindustries","federalbank","gailindia",
          "gmrairportsinfrastructure","glenmarkpharma","godrejconsumerproducts","godrejproperties","granulesindia","grasimindustries","gujaratgas",
          "gujaratnarmadavalleyfertchem","hcltechnologies","hdfcassetmanagementcompany","hdfcbank","hdfclifeinsurancecompany","havellsindia","heromotocorp",
          "hindalcoindustries","hindustanaeronauticsltd","hindustancopper","hindustanpetroleumcorporation","hindustanunilever","icicibank","icicilombardgeneralinsurancecompany",
          "iciciprudentiallifeinsurancecompany","idfcfirstbank","idfc","itc","indiacements", "indiabullshousingfinance", "indiamartintermesh","indianenergyexchange","indianhotelscompany",
          "indianoilcorporation","irctc-indianrailwaycateringtourismcorp","indraprasthagas","industowers","indusindbank","infoedgeindia", "infosys","interglobeaviation","ipcalaboratories",
          "jkcement","jswsteel","jindalsteelpower","jubilantfoodworks", "kotakmahindrabank","ltfinanceholdings","lttechnologyservices","lichousingfinance","ltimindtree","larsentoubro",
          "lauruslabs", "lupin","mrf","mahanagargas","mahindramahindrafinancialservices","mahindramahindra","manappuramfinance","marico","marutisuzukiindia","maxfinancialservices",
          "metropolishealthcare", "mphasis","multicommodityexchangeindia","muthootfinance","nmdc","ntpc","nationalaluminiumcompany","navinfluorineinternational",
          "nestleindia","oberoirealty","oilnaturalgascorporation","oraclefinancialservicessoftware","piindustries","pvrinox","pageindustries","persistentsystems",
          "petronetlng","pidiliteindustries","piramalenterprises","polycabindia","powerfinancecorporation","powergridcorporationindia","punjabnationalbank","rblbank",
          "rec","relianceindustries","sbicardspaymentservices","sbilifeinsurancecompany","srf","samvardhanamothersoninternational","shreecements","shriramfinance","siemens","statebankindia",
          "steelauthorityindia","sunpharmaceuticalindustries","suntvnetwork","syngeneinternational","tvsmotorcompany","tatachemicals","tatacommunications","tataconsultancyservices","tataconsumerproducts",
          "tatamotors", "thetatapowercompany","tatasteel","techmahindra","theramcocements","titancompany","torrentpharmaceuticals","trent", "upl","ultratechcement","unitedbreweries","unitedspirits",
          "vedanta","vodafoneidealimited","voltas","wipro","zeeentertainmententerprises","zyduslifesciences"]

ti : ["ABB", "ACC06","ASF02","AI45","AI51","AE13","MPS","ABC9","PFR","AL05","AC18","AHE" ,"AT14",
     "AL","AP31","APT02","A06","AP","AB16","BA10","BAF","BF04","BI03","BCM","BB09","BOB","BI01",
     "BPI02","BE03","BF03","BHE","BPC","BA08","BL03","KPI02","B05","BI","CFH","CB06","CFC","CDB",
     "C","CUB","CI11","NII02","CPI","CCI","CI45","CGC01","CI02","D04","DI","OCL","DN","DC11","DL03",
      "DT07","DLP01","DRL","EM", "E","EI","FB","GAI","GI27","GP08","GCP","GP11","GI25","GI01","GGC","GNV",
      "HCL02","HAM02","HDF01","HSL01","HI01","HHM","HI","HAL","HC07","HPC","HU","ICI02","ILG","IPL01","IDF01",
      "IDF","ITC","IC", "IHF01", "II12","IEE","IHC","IOC","IRC","IG04","BI14","IIB","IEI01","IT", "IA04","IL",
      "JKC03","JSW01","JSP", "JF04","KMB","LFH","LTS","LIC","LI12","LT","LL05","L","MRF","MG02","MMF04","MM","MGF01",
      "M13","MS24","MI","MH06","MB02","MCE","MF10","NMD02","NTP","NAC","NFI","NI","OR","ONG","OFS01","PII","PVR","PI35","PS15",
      "PLN","PI11","PH05","PI44","PFC02","PGC","PNB05","RB03","REC02","RI","SCP02","SLI03","SRF","MSS01","SC12","STF","S","SBI",
      "SAI","SPI","STN01","SI10","TVS","TC","TC17","TCS","TT","TM03","TPC","TIS","TM4","MC","TI01","TP06","T04","UP04","UTC01","UB02",
      "US","SG","IC8","V","W","ZEE","CHC"
     ]